# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HKBTCN' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HKBTCN

  target 'HKBTCNTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HKBTCNUITests' do
    # Pods for testing
  end

	pod 'Charts'
end
