# Uncomment the next line to define a global platform for your project
# source 'https://github.com/ABTSoftware/PodSpecs.git'
# platform :ios, '9.0'

target 'ImageLab' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageLab

  target 'ImageLabTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImageLabUITests' do
    # Pods for testing
  end

pod 'Charts' 
# pod 'SciChart' 
end
